### ISSUE TITLE
Unexpected token in collection.find({}).toArray() 

### ISSUE THREAD

**Issue by fragger87** [sergeyksv/tingodb#72] opened 2015-03-24 13:39 UTC
I've got this problem once, after series of random device resets. Generally I'm storing some data in one function and loading them with interval with collection.find({}).toArray(). Recently in this function callback 

    this.logStore.find({}).toArray(function(err,logsQueue){
            if(err) {
                console.log(preLog+err);
                setTimeout(that.shiftLogsQueue.bind(that),5000);
            }...

i've got  UNEXPECTED TOKEN in err. Is it possible that database file has crashed? After deleting db file everything worked fine again. I'm using it on embedded device so maybe FS is a problem there?

**Comment by sergeyksv** [comment] 2015-03-25 07:11
We design DB to be safe with corruptions of db that can be caused by app crashes or restarts. DB is populated using append only method and it has procedure to trim out any corrupted documents that can appears on the end of the file. If you can send the copy of your database on which you experience an issue we can try to check what happens. Thanks.

**Comment by fragger87** [comment] 2015-03-26 16:34
Hi. There is a database file:
http://mems-lab.com/wkosek/logStore

**Comment by sergeyksv** [comment] 2015-03-26 17:09
Do you mind to keep this open? Database file is corrupted (incomplete at the end) but we should be able to handle this, I'll check.

**Comment by ryansturmer** [comment] 2015-04-10 19:40
I have experienced similar issues (will follow up with a data file)

**Comment by fragger87** [comment] 2015-04-21 17:53
HI. Again same problem:
Error: logStore: Error during load - SyntaxError: Unexpected token
Any idea how to fix those database (even without last entry)
File ends on 
{"k":"0000000080","o":"0000000163","v":"001"}
{"_id":16,"_uid":16,"_dt":1429635950801,"_s":"5da86b7c68ee7d33332cd2653b33596
And it's caused by hardware reset.

**Comment by sergeyksv** [comment] 2015-04-21 18:00
Just edit file in text editor and trim it before {"k":"0000000080","o":"0000000163","v":"001"}. Keep line endings as is.

**Comment by sergeyksv** [comment] 2015-09-09 11:25
Fixed now, latest partially saved object will be removed from db

**Closed by sergeyksv** 2015-09-09 11:25 UTC
